# Generated by Django 4.0.2 on 2022-02-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited', models.CharField(max_length=50)),
                ('timeout', models.DateTimeField(verbose_name='invite timeout')),
            ],
        ),
    ]
