# Generated by Django 4.2.29 on 2026-03-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_userprofile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['buyer', 'product'], name='boutique_sa_buyer_i_409de8_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['saletime'], name='boutique_sa_saletim_ff66b4_idx'),
        ),
    ]
