# Generated by Django 4.2.30 on 2026-04-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_sale_boutique_sa_buyer_i_409de8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
