# Generated by Django 4.2.30 on 2026-04-16 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_product_offer_active_product_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='transaction',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
